[project]
name = ""
version = ""
description = ""
authors = [
    {name = "Philipp.DAngelo.external", email = "philipp_angelo@gmx.de"},
]
dependencies = []
requires-python = ">=3.10"
readme = "README.md"
license = {text = "MIT"}

[tool.pdm.dev-dependencies]
dev = [
    "pytest>=7.4.3",
]
