apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: app
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: app
    spec:
      nodeSelector:
        stage: apps
      containers:
      - image: p1containerregistry.azurecr.io/app:sqlite
        name: app
        ports:
        - containerPort: 1234
        resources: {}
        imagePullPolicy: Always
        env:
          - name: APP_DB_DRIVER
            value: "postgresql"
          - name: APP_DB_HOST
            value: "postgres.default"
          - name: APP_DB_USER
            value: "postgres"
          - name: APP_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: postgres_password 
          - name: APP_DB_DATABASE
            value: "shop"
status: {}
