apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: app
  name: app
spec:
  ports:
  - port: 1234
    protocol: TCP
    targetPort: 1234
  selector:
    app: app
status:
  loadBalancer: {}
