apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: reverse-proxy
  name: reverse-proxy
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: reverse-proxy
status:
  loadBalancer: {}
